authselect/authselect

src/lib/files/system.c
src/lib/util/string.c
src/lib/util/string.h
src/lib/util/template.c
src/tests/test_util_template.c

The following scenario triggers a bug when the line is not removed completely
and the two lines are merged instead.
```
BEGINNING {if "condition":true|false} END {include if "condition"}
NEXT LINE
->
BEGINNING falseNEXT LINE
```
This is because `match_string` points after the first condition and we
only remove the line to this point. Therefore we need to interate
before `match_string` so we can find the real line start.
Resolves:
https://github.com/authselect/authselect/issues/218

utils: correctly remove the whole line if `str` does not point to its beginning

---

profiles/Makefile.am
profiles/minimal/fingerprint-auth
profiles/minimal/smartcard-auth
profiles/nis/fingerprint-auth
profiles/nis/smartcard-auth
profiles/sssd/fingerprint-auth
profiles/sssd/smartcard-auth
profiles/winbind/fingerprint-auth
profiles/winbind/smartcard-auth
rpm/authselect.spec.in

This way if someone tries to use the stack it will return AUTHINFO_UNAVAIL.
Resolves: https://github.com/authselect/authselect/issues/238

profiles: add pam_debug to empty fingerprint and smartcard stack

---

profiles/sssd/README
profiles/sssd/REQUIREMENTS
profiles/sssd/nsswitch.conf

The passwd and group databases will now default to files first.
The order "sss files" can be enabled with "with-files-provider"
feature.
This relates to F35 change:
https://fedoraproject.org/wiki/Changes/FlexibleLocalUserCache
Resolves:
https://github.com/authselect/authselect/issues/254

sssd: default to files first for users and groups

---

src/cli/cli_tool.c

Also make --debug description the same as in cli_tool_print_common_opts.
These options are printed when a wrong argument is given on the command line. E.g.
authselect select --invalid-arg

cli: use gettext on common options

---

src/lib/authselect.c

If authselect_profile() fails, we goto done and try to free uninitialized
variable.
Resolves:
https://github.com/authselect/authselect/issues/265

lib: avoid freeing uninitialized variable in authselect_apply_changes()

---

rpm/authselect.spec.in

spec: remove translations.tgz from spec file for rhel

---

rpm/authselect.spec.in

All rpm-ostree based systems currently rely on nss-altfiles for user and
group lookups. Thus generalize the logic to match for 'OSTREE_VERSION'
instead of specific variants during installation.
See: https://github.com/authselect/authselect/issues/48
Fixes: https://github.com/authselect/authselect/commit/c2b1b7a72b8b2efb3c244feca65abd692b0ed599
Fixes: https://github.com/authselect/authselect/commit/9e14ff3cd1cb8a84561d1b8adeaf00c42c4ce5c4

authselect.spec: Add nss-altfiles for all ostree systems

---

src/cli/main.c

From `man free()`:
```
The free() function frees the memory space pointed to by ptr ...  If ptr is NULL, no operation is performed.
```
Obviously there are *tons* of these in the codebase; just doing
this one as a preliminary PR; if accepted I may do some more, or
others can.  Or we could try a coccinelle semantic patch.

main: Drop an unnecessary `NULL` check before `free()`

---

profiles/nis/README
profiles/nis/REQUIREMENTS
profiles/nis/fingerprint-auth
profiles/nis/password-auth
profiles/nis/system-auth
profiles/sssd/README
profiles/sssd/REQUIREMENTS
profiles/sssd/fingerprint-auth
profiles/sssd/password-auth
profiles/sssd/smartcard-auth
profiles/sssd/system-auth
profiles/winbind/README
profiles/winbind/REQUIREMENTS
profiles/winbind/fingerprint-auth
profiles/winbind/password-auth
profiles/winbind/system-auth

Currently the default profiles don't have the ability to enable the use of pam_gnome_keyring module.  This update adds a 'with-pam-gnome-keyring' feature to the default profiles.
The feature does not enable the feature by default.  
This update should have no impact on current installs.  This an opt-in feature.

Added feature with-pam-gnome-keyring.

---

src/lib/authselect_backup.c

The restore process did not write configuration copy to
/var/lib/authselect which made the restoration incomplete
and `authselect check` then failed.
Steps to reproduce:
1. authselect select sssd --force
2. authselect enable-feature with-mkhomedir
3. authselect apply-changes --backup=test
4. authselect backup-restore test
5. authselect check
`authselect check` will fail without this patch.
Resolves: https://github.com/authselect/authselect/issues/302

lib: correctly restore authselect backup

---

src/cli/cli_tool.c
src/cli/cli_tool.h
src/cli/main.c

This patch makes a copy of the string returned by popt so
the string can be safely used after releasing popt context.
Resolves: https://github.com/authselect/authselect/issues/313

cli: fix memory handling with new popt library

---

src/man/authselect.8.adoc

Resolves: https://github.com/authselect/authselect/issues/315

man: remove --custom from create-profile which does not exist

---

profiles/nis/README
profiles/nis/REQUIREMENTS
profiles/nis/nsswitch.conf
profiles/sssd/README
profiles/sssd/REQUIREMENTS
profiles/sssd/nsswitch.conf
profiles/winbind/README
profiles/winbind/REQUIREMENTS
profiles/winbind/nsswitch.conf

The libvirt NSS plugins can be used to conveniently connect to VMs running on the system.
See [https://libvirt.org/nss.html](https://libvirt.org/nss.html) for additional information. Once this is merged, I will update that page to advertise authselect as the preferred mechanism to enable the feature.
This is my first time contributing to authselect, so please don't hesitate to point out any mistake I might have made :)

profiles: Add with-libvirt feature

---

profiles/minimal/nsswitch.conf
profiles/nis/nsswitch.conf
profiles/sssd/nsswitch.conf
profiles/winbind/nsswitch.conf

nss_systemd also implements shadow and gshadow so it should be set
for these databases as well.

profiles: add systemd to nsswitch shadow and gshadow

---

scripts/manpages-install.sh.in

Fix errors when required command (find, basename, sed, install) can be found somewhere else; don't using system enviroment variable PATH with brokes normal command invocations.

Fix installation of manpage

---

src/compat/authcompat.py.in.in

SSSD ignores the snippet otherwise.

compat: chmod sssd snippet to 0600

---

profiles/sssd/password-auth
profiles/sssd/system-auth

Steps to reproduce:
1. Create local user and set passsword
2. Log in as the local user
3. Run passwd and provide wrong password as "Current password"
"Current password" prompt should be printed only once.
Resolves: https://github.com/authselect/authselect/issues/338

profiles: do not try to change password via sssd for local users

---

src/lib/util/selinux.c

So it does not get confused with selinux context.

selinux: correct error message

---

profiles/sssd/README
profiles/sssd/fingerprint-auth
profiles/sssd/password-auth
profiles/sssd/smartcard-auth
profiles/sssd/system-auth

This is still needed to support .k5login file with proxy domain. For
example:
```
[domain/proxy]
id_provider = proxy
proxy_lib_name = files
access_provider = krb5
auth_provider = krb5
krb5_server = kdc.test
krb5_realm = TEST
```

sssd: reintroduce with-files-access-provider

---

rpm/authselect.spec.in

- conditionals that are no longer used are removed
- upgrade path is removed
- this was already triggered in Fedora 38, so it is no longer useful
- RHEL is updated to authselect with leapp when going from 7 to 8
we don't want to touch existing configurations

spec: modify specfile for Fedora 40 and RHEL 10 as minimal version

---

profiles/local/nsswitch.conf
profiles/nis/nsswitch.conf
profiles/sssd/nsswitch.conf
profiles/winbind/nsswitch.conf
rpm/authselect.spec.in

Services such as systemd-homed would like to advertise users which are part of system groups, such as "wheel". That only works if glibc's [SUCCESS=merge] feature is used in nsswitch.conf, so that group records from multiple sources are merged.
This is documented here:
https://www.freedesktop.org/software/systemd/man/latest/nss-systemd.html#Configuration%20in%20/etc/nsswitch.conf
This hence adds [SUCCESS=merge] expressions to all NSS modules listed in the "groups" lines.

profiles: merge groups records with [SUCCESS=merge]

---

rpm/authselect.spec.in

The regex that was given matched the `group` line but not the `passwd` line (which doesn't have that `[SUCCESS=merge]` bit).
Generalize the regex instead so that we just take whatever the contents of the conditional was and put it in there.
Fixes: https://github.com/coreos/fedora-coreos-tracker/issues/1680
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2266344
(Upstreamed from https://src.fedoraproject.org/rpms/authselect/pull-request/22)

spec: strengthen altfiles sed invocation

---

src/tests/system/conftest.py
src/tests/system/mhc.yaml
src/tests/system/polarion.yaml
src/tests/system/pyproject.toml
src/tests/system/pytest.ini
src/tests/system/requirements.txt
src/tests/system/setup.cfg
src/tests/system/tests/test_local.py
src/tests/system/tests/test_sssd.py

- adding authselect tests
- adding test files copied from sssd 
- conftest.py
- data/readme.md
- pytest.ini
- pyproject.toml
- requirements.txt
- setup.cfg

tests: ported authselect tests from downstream

---

.packit.yaml

Hello @pbrezina, I'm opening this PR in response to https://github.com/packit/packit-service/issues/2372.
Packit configuration I've added includes both upstream and downstream jobs.
As for upstream, there is a `copr_build` job that builds authselect in Copr in the specified chroots on every pull request. You can see the results [here](https://github.com/nforro/authselect/pull/1/checks) on my fork. To enable it in this repository, please follow our [onboarding guide](https://packit.dev/docs/guide#how-to-set-up-packit-on-github) and install the *Packit-as-a-Service* GitHub application.
As for downstream, there is a `propose_downstream` job that updates authselect in dist-git when a new GitHub release is published and opens a pull request with the changes. I've only enabled this for rawhide, …

Add Packit configuration

---

profiles/local/nsswitch.conf
profiles/nis/nsswitch.conf
profiles/sssd/nsswitch.conf
profiles/winbind/nsswitch.conf

Since systemd v249 (2021) nss-systemd hasn't just been generating entries in the "passwd" and "group" databases, but in "shadow" and "gshadow" as well. This is documented in the man page:
https://www.freedesktop.org/software/systemd/man/latest/nss-systemd.html
This is generally useful, since various account validity fields that userdb/homed maintains are only exported via spwd/sgrp, but most importantly this makes the "systemd-nspawn --bind-user=" logic work, which just propagates the hashed user pw into a container.
The patch is pretty simple: in all profiles where passwd/group already lists "systemd", we also add it to the lines with shadow/spwd, to the end.

profiles: include "systemd" in shadow + gshadow nsswitch.conf lines

---

src/tests/test_common.h

Currently, authselect does not build with cmocka 1.1.8, due to missing includes towards `stdint.h`:
```
2025-07-18 14:45:49 make[2]: Leaving directory '/home/lkp/rpmbuild/BUILD/authselect-1.5.0/src/tests'
2025-07-18 14:45:49 In file included from ../../src/tests/test_common.h:39,
2025-07-18 14:45:49                  from test_util_string_array.c:24:
2025-07-18 14:45:49 test_util_string_array.c: In function 'test_string_array_create':
2025-07-18 14:45:49 test_util_string_array.c:32:5: error: 'uintptr_t' undeclared (first use in this function)
2025-07-18 14:45:49    32 |     assert_non_null(array);
2025-07-18 14:45:49       |     ^~~~~~~~~~~~~~~
2025-07-18 14:45:49 test_util_string_array.c:26:1: note: 'uintptr_t' is defined in header '<stdint.h>'; did you forget to '#include <stdint.h>'? …
```

tests: add missing include for stdint
